apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ps-pvc
  namespace: psns
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile-csi
  resources:
    requests:
      storage: 5Gi
